language: cpp
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - clang-4.0

before_install:
# Clone private dependencies which are not part of the main repository
  - cd ..
  - git clone https://$INTR_GIT_TOKEN@github.com/begla/Intrinsic_Dependencies.git
  - cd Intrinsic
  
install:
# SDL2
  - curl -O http://libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
  
# Vulkan SDK
  - curl https://vulkan.lunarg.com/sdk/download/1.0.51.0/linux/vulkansdk-linux-x86_64-1.0.51.0.run -L -o vulkan.run
  - chmod +x vulkan.run
  - ./vulkan.run
  
# Build dependencies
  - cd scripts_linux
  - chmod +x ConfigAndBuildDependencies
  - ./ConfigAndBuildDependencies
  - cd ..
  
script:
  - export VK_SDK_PATH=$(pwd)/VulkanSDK/1.0.51.0/x86_64/

# Config via CMake
  - cd scripts_linux
  - ./Config_Release
  - ./Build
  - cd ..
